// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Abstract_Christmas_Tree_glb = "Abstract_Christmas_Tree.glb",
  Abstract_Christmas_Tree_glb_10 = "Abstract_Christmas_Tree.glb_10",
  Abstract_Christmas_Tree_glb_11 = "Abstract_Christmas_Tree.glb_11",
  Abstract_Christmas_Tree_glb_12 = "Abstract_Christmas_Tree.glb_12",
  Abstract_Christmas_Tree_glb_13 = "Abstract_Christmas_Tree.glb_13",
  Abstract_Christmas_Tree_glb_14 = "Abstract_Christmas_Tree.glb_14",
  Abstract_Christmas_Tree_glb_15 = "Abstract_Christmas_Tree.glb_15",
  Abstract_Christmas_Tree_glb_3 = "Abstract_Christmas_Tree.glb_3",
  Abstract_Christmas_Tree_glb_4 = "Abstract_Christmas_Tree.glb_4",
  Abstract_Christmas_Tree_glb_5 = "Abstract_Christmas_Tree.glb_5",
  Abstract_Christmas_Tree_glb_6 = "Abstract_Christmas_Tree.glb_6",
  Abstract_Christmas_Tree_glb_7 = "Abstract_Christmas_Tree.glb_7",
  Abstract_Christmas_Tree_glb_8 = "Abstract_Christmas_Tree.glb_8",
  Abstract_Christmas_Tree_glb_9 = "Abstract_Christmas_Tree.glb_9",
  AccentColorStage = "AccentColorStage",
  AccentColorStage_BelowPodium = "AccentColorStage_BelowPodium",
  Admin_Tools = "Admin Tools",
  AttendeePanel = "AttendeePanel",
  AuditoriumCamera = "AuditoriumCamera",
  BannerBackground = "BannerBackground",
  BannerBackground_2 = "BannerBackground_2",
  BannerLogo = "BannerLogo",
  BannerLogo_2 = "BannerLogo_2",
  Cylinder = "Cylinder",
  Cylinder_2 = "Cylinder_2",
  Cylinder_3 = "Cylinder_3",
  Fireworks = "Fireworks",
  Fireworks_2 = "Fireworks_2",
  Fireworks_3 = "Fireworks_3",
  Fireworks_4 = "Fireworks_4",
  Fireworks_5 = "Fireworks_5",
  Fireworks_6 = "Fireworks_6",
  Interactable = "Interactable",
  Logo = "Logo",
  Podium = "Podium",
  Rounded_Video_Screen = "Rounded Video Screen",
  Stage = "Stage",
  StageWall = "StageWall",
  Trees = "Trees",
  VotingDoor1 = "VotingDoor1",
  VotingDoor2 = "VotingDoor2",
  VotingDoor3 = "VotingDoor3",
  VotingDoor4 = "VotingDoor4",
  VotingZone1 = "VotingZone1",
  VotingZone2 = "VotingZone2",
  VotingZone3 = "VotingZone3",
  VotingZone4 = "VotingZone4",
  explosion = "explosion",
  explosion_2 = "explosion_2",
  explosion_3 = "explosion_3",
  gift1 = "gift1",
  gift2 = "gift2",
  gift2_2 = "gift2_2",
  gift2_3 = "gift2_3",
  gift3 = "gift3",
  gift3_2 = "gift3_2",
  gift3_3 = "gift3_3",
  gifts = "gifts",
  grades = "grades",
  stage_gltf = "stage.gltf",
  teamhub = "teamhub",
} 
